# Generated by Django 4.1.6 on 2023-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmobilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mapp/static')),
                ('mname', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
