# Generated by Django 4.1.6 on 2023-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_addmobilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmobilemodel',
            name='image',
            field=models.ImageField(upload_to='smartapp/static'),
        ),
    ]
