# Generated by Django 4.1.6 on 2023-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0005_addpartsmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='partsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='smartapp/static')),
                ('pname', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='addpartsmodel',
        ),
    ]
