# Generated by Django 4.1.6 on 2023-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0009_alter_repairinfomodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='buypartsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=70)),
                ('fname', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('paymode', models.CharField(choices=[('Debit/Credit Card', 'Debit/Credit Card'), ('Upi', 'Upi'), ('Cash on delivery', 'Cash on delivery')], max_length=50)),
            ],
        ),
    ]
