# Generated by Django 4.1.6 on 2023-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0010_buypartsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='recyclemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=70)),
                ('fname', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
