# Generated by Django 4.1.6 on 2023-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0013_writereviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='writereviewmodel',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
